cve: CVE-2010-3495
description: Race condition in ZEO/StorageServer.py in Zope Object Database (ZODB)
  before 3.10.0 allows remote attackers to cause a denial of service (daemon outage)
  by establishing and then immediately closing a TCP connection, leading to the accept
  function having an unexpected return value of None, an unexpected value of None
  for the address, or an ECONNABORTED, EAGAIN, or EWOULDBLOCK error, a related issue
  to CVE-2010-3492.
package: zodb
urls:
- http://www.openwall.com/lists/oss-security/2010/09/09/6
- http://www.openwall.com/lists/oss-security/2010/09/11/2
- http://www.openwall.com/lists/oss-security/2010/09/22/3
- http://www.openwall.com/lists/oss-security/2010/09/24/3
- http://bugs.python.org/issue6706
- http://pypi.python.org/pypi/ZODB3/3.10.0#id1
- https://bugs.launchpad.net/zodb/+bug/135108
- http://lists.opensuse.org/opensuse-security-announce/2010-12/msg00006.html
- http://secunia.com/advisories/41755
versions:
- <3.10.0
